-- Randomizer application schema
-- Target database: PostgreSQL 14+
-- Passwords should be stored as strong hashes generated by the backend
-- application, never as plaintext.

-- Drop existing tables if they exist to allow clean reset
DROP TABLE IF EXISTS public.export_files CASCADE;
DROP TABLE IF EXISTS public.prize_payouts CASCADE;
DROP TABLE IF EXISTS public.number_bets CASCADE;
DROP TABLE IF EXISTS public.tickets CASCADE;
DROP TABLE IF EXISTS public.booklet_sheets CASCADE;
DROP TABLE IF EXISTS public.booklets CASCADE;
DROP TABLE IF EXISTS public.winning_numbers CASCADE;
DROP TABLE IF EXISTS public.batch_draw_revenue_percentages CASCADE;
DROP TABLE IF EXISTS public.batches CASCADE;
DROP TABLE IF EXISTS public.game_types CASCADE;
DROP TABLE IF EXISTS public.companies CASCADE;
DROP TABLE IF EXISTS public.login_events CASCADE;
DROP TABLE IF EXISTS public.user_sessions CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- Drop existing types if they exist
DROP TYPE IF EXISTS public.user_role CASCADE;
DROP TYPE IF EXISTS public.user_status CASCADE;
DROP TYPE IF EXISTS public.batch_status CASCADE;
DROP TYPE IF EXISTS public.game_format CASCADE;

CREATE TYPE user_role AS ENUM ('admin', 'manager', 'viewer');
CREATE TYPE user_status AS ENUM ('active', 'disabled', 'locked');
CREATE TYPE batch_status AS ENUM ('pending', 'generated', 'approved', 'voided');
CREATE TYPE game_format AS ENUM ('standard', '3D', 'L3D');

CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    company_id BIGINT,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    full_name TEXT NOT NULL,
    role user_role NOT NULL DEFAULT 'manager',
    status user_status NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMPTZ,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT users_email_lowercase CHECK (email = lower(email)),
    CONSTRAINT users_failed_login_attempts_nonnegative CHECK (failed_login_attempts >= 0)
);

CREATE TABLE user_sessions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token_hash TEXT NOT NULL UNIQUE,
    user_agent TEXT,
    ip_address INET,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT user_sessions_valid_expiry CHECK (expires_at > created_at)
);

CREATE TABLE login_events (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    email TEXT NOT NULL,
    succeeded BOOLEAN NOT NULL,
    failure_reason TEXT,
    ip_address INET,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE companies (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    address TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT companies_code_uppercase CHECK (code = upper(code))
);

ALTER TABLE users
    ADD CONSTRAINT users_company_id_fkey
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;

CREATE TABLE game_types (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    digits INTEGER NOT NULL,
    multiplier INTEGER NOT NULL,
    draw_time TIME,
    is_national BOOLEAN NOT NULL DEFAULT false,
    format game_format NOT NULL DEFAULT 'standard',
    number_range_min INTEGER,
    number_range_max INTEGER,
    ekis_multiplier INTEGER,
    rumble_multiplier INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CONSTRAINT game_types_digits_positive CHECK (digits > 0),
    CONSTRAINT game_types_multiplier_positive CHECK (multiplier > 0),
    CONSTRAINT game_types_range_valid CHECK (
        number_range_min IS NULL
        OR number_range_max IS NULL
        OR number_range_min <= number_range_max
    )
);

CREATE TABLE batches (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    batch_code TEXT NOT NULL UNIQUE,
    company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    province TEXT NOT NULL,
    batch_date DATE NOT NULL,
    status batch_status NOT NULL DEFAULT 'pending',
    total_booklets INTEGER NOT NULL DEFAULT 0,
    total_revenue NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_payout NUMERIC(14, 2) NOT NULL DEFAULT 0,
    generated_at TIMESTAMPTZ,
    approved_at TIMESTAMPTZ,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    approved_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT batches_booklets_nonnegative CHECK (total_booklets >= 0),
    CONSTRAINT batches_revenue_nonnegative CHECK (total_revenue >= 0),
    CONSTRAINT batches_payout_nonnegative CHECK (total_payout >= 0)
);

CREATE TABLE batch_draw_revenue_percentages (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    game_type_id BIGINT NOT NULL REFERENCES game_types(id) ON DELETE CASCADE,
    percentage NUMERIC(6, 3) NOT NULL,
    UNIQUE (batch_id, game_type_id),
    CONSTRAINT batch_draw_revenue_percentages_range CHECK (percentage >= 0 AND percentage <= 100)
);

CREATE TABLE winning_numbers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    game_type_id BIGINT NOT NULL REFERENCES game_types(id) ON DELETE RESTRICT,
    winning_number TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (batch_id, game_type_id)
);

CREATE TABLE booklets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    booklet_number INTEGER NOT NULL,
    revenue NUMERIC(14, 2) NOT NULL DEFAULT 0,
    payout NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_bets NUMERIC(14, 2) NOT NULL DEFAULT 0,
    serial_start TEXT,
    serial_end TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (batch_id, booklet_number),
    CONSTRAINT booklets_number_positive CHECK (booklet_number > 0),
    CONSTRAINT booklets_revenue_nonnegative CHECK (revenue >= 0),
    CONSTRAINT booklets_payout_nonnegative CHECK (payout >= 0),
    CONSTRAINT booklets_total_bets_nonnegative CHECK (total_bets >= 0)
);

CREATE TABLE booklet_sheets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    booklet_id BIGINT NOT NULL REFERENCES booklets(id) ON DELETE CASCADE,
    sheet_number INTEGER NOT NULL,
    sheet_code TEXT,
    total_bets NUMERIC(14, 2) NOT NULL DEFAULT 0,
    game_type_id BIGINT REFERENCES game_types(id) ON DELETE SET NULL,
    UNIQUE (booklet_id, sheet_number),
    CONSTRAINT booklet_sheets_number_positive CHECK (sheet_number > 0),
    CONSTRAINT booklet_sheets_total_bets_nonnegative CHECK (total_bets >= 0)
);

CREATE TABLE tickets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sheet_id BIGINT NOT NULL REFERENCES booklet_sheets(id) ON DELETE CASCADE,
    ticket_label TEXT NOT NULL,
    serial_number TEXT NOT NULL UNIQUE,
    game_type_id BIGINT REFERENCES game_types(id) ON DELETE SET NULL,
    ticket_total NUMERIC(14, 2) NOT NULL DEFAULT 0,
    ticket_order INTEGER NOT NULL,
    CONSTRAINT tickets_label_valid CHECK (ticket_label IN ('A', 'B', 'C', 'D', 'E')),
    CONSTRAINT tickets_order_positive CHECK (ticket_order > 0),
    CONSTRAINT tickets_total_nonnegative CHECK (ticket_total >= 0)
);

CREATE TABLE number_bets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    game_type_id BIGINT NOT NULL REFERENCES game_types(id) ON DELETE RESTRICT,
    slot_number INTEGER NOT NULL,
    combination TEXT NOT NULL,
    bet_amount NUMERIC(14, 2) NOT NULL,
    is_winner BOOLEAN NOT NULL DEFAULT false,
    payout_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    UNIQUE (ticket_id, slot_number),
    CONSTRAINT number_bets_slot_range CHECK (slot_number BETWEEN 1 AND 3),
    CONSTRAINT number_bets_amount_positive CHECK (bet_amount > 0),
    CONSTRAINT number_bets_payout_nonnegative CHECK (payout_amount >= 0)
);

CREATE TABLE prize_payouts (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    booklet_id BIGINT NOT NULL REFERENCES booklets(id) ON DELETE CASCADE,
    number_bet_id BIGINT NOT NULL REFERENCES number_bets(id) ON DELETE CASCADE,
    winner_name TEXT,
    amount NUMERIC(14, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (number_bet_id),
    CONSTRAINT prize_payouts_amount_positive CHECK (amount > 0)
);

CREATE TABLE export_files (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    batch_id BIGINT REFERENCES batches(id) ON DELETE CASCADE,
    export_type TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_path TEXT,
    generated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX idx_user_sessions_expires_at ON user_sessions(expires_at);
CREATE INDEX idx_login_events_email_created_at ON login_events(email, created_at DESC);
CREATE INDEX idx_users_auth_user_id ON users(auth_user_id);
CREATE INDEX idx_users_company_id ON users(company_id);
CREATE INDEX idx_companies_created_by_user_id ON companies(created_by_user_id);
CREATE INDEX idx_game_types_company_id ON game_types(company_id);
CREATE INDEX idx_batches_company_date ON batches(company_id, batch_date DESC);
CREATE INDEX idx_batches_created_by_user_id ON batches(created_by_user_id);
CREATE INDEX idx_booklets_batch_id ON booklets(batch_id);
CREATE INDEX idx_booklet_sheets_booklet_id ON booklet_sheets(booklet_id);
CREATE INDEX idx_tickets_sheet_id ON tickets(sheet_id);
CREATE INDEX idx_tickets_serial_number ON tickets(serial_number);
CREATE INDEX idx_number_bets_ticket_id ON number_bets(ticket_id);
CREATE INDEX idx_number_bets_game_winner ON number_bets(game_type_id, is_winner);
CREATE INDEX idx_prize_payouts_batch_id ON prize_payouts(batch_id);

-- ==========================================
-- Sample Seed Data
-- ==========================================

-- 1. Insert a sample company
INSERT INTO companies (name, code, address, contact_email)
VALUES (
    'Lanao del Norte - Glowing Fortune',
    'LDN',
    'Lanao del Norte',
    'lanaonorte.manager@glowingfortune.com'
) ON CONFLICT (code) DO NOTHING;

-- 2. Insert sample game types corresponding to frontend configurations
INSERT INTO game_types (company_id, code, name, digits, multiplier, draw_time, is_national, format)
SELECT id, 'l3d-local-1030', 'Local 3D 10:30 AM', 3, 550, '10:30:00'::time, false, 'L3D'::game_format FROM companies WHERE code = 'LDN'
ON CONFLICT (company_id, code) DO NOTHING;

INSERT INTO game_types (company_id, code, name, digits, multiplier, draw_time, is_national, format)
SELECT id, '3d-national-1400', '3D 2:00 PM', 3, 500, '14:00:00'::time, true, '3D'::game_format FROM companies WHERE code = 'LDN'
ON CONFLICT (company_id, code) DO NOTHING;

INSERT INTO game_types (company_id, code, name, digits, multiplier, draw_time, is_national, format)
SELECT id, 'l3d-local-1500', 'Local 3D 3:00 PM', 3, 550, '15:00:00'::time, false, 'L3D'::game_format FROM companies WHERE code = 'LDN'
ON CONFLICT (company_id, code) DO NOTHING;

INSERT INTO game_types (company_id, code, name, digits, multiplier, draw_time, is_national, format)
SELECT id, '3d-national-1700', '3D 5:00 PM', 3, 500, '17:00:00'::time, true, '3D'::game_format FROM companies WHERE code = 'LDN'
ON CONFLICT (company_id, code) DO NOTHING;

INSERT INTO game_types (company_id, code, name, digits, multiplier, draw_time, is_national, format)
SELECT id, 'l3d-local-1900', 'Local 3D 7:00 PM', 3, 550, '19:00:00'::time, false, 'L3D'::game_format FROM companies WHERE code = 'LDN'
ON CONFLICT (company_id, code) DO NOTHING;

INSERT INTO game_types (company_id, code, name, digits, multiplier, draw_time, is_national, format)
SELECT id, '3d-national-2100', '3D 9:00 PM', 3, 500, '21:00:00'::time, true, '3D'::game_format FROM companies WHERE code = 'LDN'
ON CONFLICT (company_id, code) DO NOTHING;
